#!/bin/bash
#
# Pi CRT Toolkit - Boot Configuration
# Manages /boot/config.txt settings for CRT output
#

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/platform.sh"

# Marker comments for our config section
CONFIG_START="# === Pi CRT Toolkit Start ==="
CONFIG_END="# === Pi CRT Toolkit End ==="

#
# sdtv_mode values
#
declare -A SDTV_MODES=(
    ["ntsc480i"]=0     # NTSC 480i (default)
    ["ntsc240p"]=16    # NTSC 240p
    ["pal576i"]=2      # PAL 576i
    ["pal288p"]=18     # PAL 288p
)

#
# Framebuffer sizes
#
declare -A FB_SIZES=(
    ["ntsc480i"]="720 480"
    ["ntsc240p"]="720 448"
    ["pal576i"]="720 576"
    ["pal288p"]="720 576"
)

#
# Config file manipulation
#

get_config_file() {
    get_config_path
}

# Backup config file
backup_config() {
    local config_file=$(get_config_file)
    local backup="${config_file}.bak.$(date +%Y%m%d-%H%M%S)"
    cp "$config_file" "$backup"
    echo "Backed up to: $backup"
}

# Remove our config section
remove_our_config() {
    local config_file=$(get_config_file)
    
    # Remove everything between our markers (inclusive)
    sed -i "/$CONFIG_START/,/$CONFIG_END/d" "$config_file"
}

# Generate config for specific OS/driver combo
generate_config() {
    local boot_mode="${1:-ntsc480i}"
    local driver="${2:-$DRIVER}"
    local os_gen="${3:-$OS_GENERATION}"
    
    local sdtv_mode="${SDTV_MODES[$boot_mode]:-0}"
    local fb_size="${FB_SIZES[$boot_mode]:-720 480}"
    read -r fb_width fb_height <<< "$fb_size"
    
    cat << EOF
$CONFIG_START
# Generated by Pi CRT Toolkit
# OS: $os_gen, Driver: $driver, Mode: $boot_mode

EOF

    # Pi4-specific section
    if [[ "$PI_MODEL" == "pi4" ]]; then
        cat << EOF
[pi4]
EOF
    fi
    
    # Driver overlay
    case "$driver" in
        fkms)
            cat << EOF
# FKMS driver (tvservice available)
dtoverlay=vc4-fkms-v3d
EOF
            ;;
        kms)
            cat << EOF
# Full KMS driver (no tvservice)
dtoverlay=vc4-kms-v3d
EOF
            ;;
        legacy)
            cat << EOF
# Legacy driver (full tvservice support)
# No dtoverlay needed
EOF
            ;;
    esac
    
    cat << EOF
max_framebuffers=2

# Composite TV output
enable_tvout=1
sdtv_mode=$sdtv_mode
sdtv_aspect=1
disable_overscan=1

# Framebuffer size
framebuffer_width=$fb_width
framebuffer_height=$fb_height

# Force composite (ignore HDMI)
hdmi_ignore_hotplug=1

# Better audio on analog output
audio_pwm_mode=2
EOF

    # Bookworm-specific settings
    if [[ "$os_gen" == "bookworm" ]]; then
        cat << EOF

# Bookworm-specific
# Note: tvservice may not work, using DRM instead
EOF
    fi
    
    # Close pi4 section if opened
    if [[ "$PI_MODEL" == "pi4" ]]; then
        cat << EOF

[all]
EOF
    fi
    
    cat << EOF
$CONFIG_END
EOF
}

# Apply config to boot file
apply_boot_config() {
    local boot_mode="${1:-ntsc480i}"
    
    init_platform
    
    local config_file=$(get_config_file)
    
    # Backup first
    backup_config
    
    # Remove existing toolkit config
    remove_our_config
    
    # Append new config
    generate_config "$boot_mode" >> "$config_file"
    
    echo "Boot configuration updated for mode: $boot_mode"
    echo "Please reboot to apply changes."
}

# Read current boot config
get_boot_config() {
    local config_file=$(get_config_file)
    
    # Extract our section if it exists
    if grep -q "$CONFIG_START" "$config_file"; then
        sed -n "/$CONFIG_START/,/$CONFIG_END/p" "$config_file"
    else
        echo "No CRT Toolkit configuration found in $config_file"
    fi
}

# Validate config file
validate_config() {
    local config_file=$(get_config_file)
    local issues=()
    
    # Check for conflicting overlays
    local fkms_count=$(grep -c "vc4-fkms-v3d" "$config_file" | grep -v "^#" || echo 0)
    local kms_count=$(grep -c "vc4-kms-v3d" "$config_file" | grep -v "^#" || echo 0)
    
    if [[ "$fkms_count" -gt 1 ]]; then
        issues+=("Multiple vc4-fkms-v3d overlays found")
    fi
    
    if [[ "$kms_count" -gt 0 ]] && [[ "$fkms_count" -gt 0 ]]; then
        issues+=("Both fkms and kms overlays found - choose one")
    fi
    
    # Check enable_tvout
    if ! grep -q "enable_tvout=1" "$config_file"; then
        issues+=("enable_tvout=1 not found - composite may not work")
    fi
    
    if [[ ${#issues[@]} -eq 0 ]]; then
        echo "Configuration looks OK"
        return 0
    else
        echo "Configuration issues found:"
        for issue in "${issues[@]}"; do
            echo "  - $issue"
        done
        return 1
    fi
}

# CLI interface
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    case "${1:-}" in
        apply)
            apply_boot_config "${2:-ntsc480i}"
            ;;
        show)
            get_boot_config
            ;;
        generate)
            init_platform
            generate_config "${2:-ntsc480i}"
            ;;
        validate)
            init_platform
            validate_config
            ;;
        backup)
            backup_config
            ;;
        *)
            echo "Usage: $0 <apply|show|generate|validate|backup> [mode]"
            echo ""
            echo "Modes: ntsc480i, ntsc240p, pal576i, pal288p"
            exit 1
            ;;
    esac
fi
