#!/bin/bash
#
# Pi CRT Toolkit - Boot Configuration
# Manages /boot/config.txt and cmdline.txt settings for CRT output
#
# Supports:
# - Buster (Debian 10): Legacy driver, /boot/config.txt
# - Bullseye (Debian 11): FKMS default, /boot/config.txt
# - Bookworm (Debian 12): Full KMS, /boot/firmware/config.txt
# - Trixie (Debian 13): Full KMS only, /boot/firmware/config.txt
#

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/platform.sh"

# Marker comments for our config section
CONFIG_START="# === Pi CRT Toolkit Start ==="
CONFIG_END="# === Pi CRT Toolkit End ==="

#
# sdtv_mode values (for FKMS/Legacy)
#
declare -A SDTV_MODES=(
    ["ntsc480i"]=0     # NTSC 480i (default)
    ["ntsc240p"]=16    # NTSC 240p
    ["pal576i"]=2      # PAL 576i
    ["pal288p"]=18     # PAL 288p
)

#
# Framebuffer sizes
#
declare -A FB_SIZES=(
    ["ntsc480i"]="720 480"
    ["ntsc240p"]="720 448"
    ["pal576i"]="720 576"
    ["pal288p"]="720 576"
)

#
# Config file manipulation
#

get_config_file() {
    get_config_path
}

get_cmdline_file() {
    get_cmdline_path
}

# Backup config file
backup_config() {
    local config_file=$(get_config_file)
    local backup="${config_file}.bak.$(date +%Y%m%d-%H%M%S)"
    cp "$config_file" "$backup"
    echo "Backed up to: $backup"
}

# Remove our config section from config.txt
remove_our_config() {
    local config_file=$(get_config_file)
    
    # Remove everything between our markers (inclusive)
    sed -i "/$CONFIG_START/,/$CONFIG_END/d" "$config_file"
}

# Comment out conflicting dtoverlays
disable_conflicting_overlays() {
    local config_file=$(get_config_file)
    local target_driver="$1"
    
    if [[ "$target_driver" == "kms" ]]; then
        # Comment out fkms if we want kms
        sed -i 's/^dtoverlay=vc4-fkms-v3d/#dtoverlay=vc4-fkms-v3d  # disabled for CRT/' "$config_file"
    elif [[ "$target_driver" == "fkms" ]]; then
        # Comment out kms if we want fkms
        sed -i 's/^dtoverlay=vc4-kms-v3d$/#dtoverlay=vc4-kms-v3d  # disabled for CRT/' "$config_file"
        # Also handle kms with options
        sed -i 's/^dtoverlay=vc4-kms-v3d,/#dtoverlay=vc4-kms-v3d,  # disabled for CRT  # was: /' "$config_file"
    fi
}

# Generate config for specific OS/driver combo
generate_config() {
    local boot_mode="${1:-ntsc480i}"
    local driver="${2:-$DRIVER}"
    local os_gen="${3:-$OS_GENERATION}"
    
    local sdtv_mode="${SDTV_MODES[$boot_mode]:-0}"
    local fb_size="${FB_SIZES[$boot_mode]:-720 480}"
    read -r fb_width fb_height <<< "$fb_size"
    
    cat << EOF
$CONFIG_START
# Generated by Pi CRT Toolkit
# OS: $os_gen, Driver: $driver, Mode: $boot_mode

EOF

    # Pi4-specific section
    if [[ "$PI_MODEL" == "pi4" ]]; then
        cat << EOF
[pi4]
EOF
    fi
    
    # Driver overlay - different for Trixie/Bookworm vs older
    case "$os_gen" in
        trixie|bookworm)
            # Trixie/Bookworm: Full KMS with ,composite option
            # See: https://www.raspberrypi.com/documentation/computers/config_txt.html
            cat << EOF
# Full KMS driver with composite output (Trixie/Bookworm)
# Composite is enabled via ,composite parameter
# Color mode is set via vc4.tv_norm in cmdline.txt
dtoverlay=vc4-kms-v3d,composite
max_framebuffers=2

# TV output settings
sdtv_mode=$sdtv_mode
sdtv_aspect=1
disable_overscan=1

# Framebuffer size
framebuffer_width=$fb_width
framebuffer_height=$fb_height

# Force composite (ignore HDMI)
hdmi_ignore_hotplug=1

# Better audio on analog output
audio_pwm_mode=2
EOF
            ;;
        bullseye)
            # Bullseye: FKMS works well with tvservice
            cat << EOF
# FKMS driver (tvservice available for runtime switching)
dtoverlay=vc4-fkms-v3d
max_framebuffers=2

# Composite TV output
enable_tvout=1
sdtv_mode=$sdtv_mode
sdtv_aspect=1
disable_overscan=1

# Framebuffer size
framebuffer_width=$fb_width
framebuffer_height=$fb_height

# Force composite (ignore HDMI)
hdmi_ignore_hotplug=1

# Better audio on analog output
audio_pwm_mode=2
EOF
            ;;
        buster|*)
            # Buster/Legacy: enable_tvout with optional fkms
            cat << EOF
# Legacy/FKMS driver (full tvservice support)
enable_tvout=1
sdtv_mode=$sdtv_mode
sdtv_aspect=1
disable_overscan=1

# Framebuffer size
framebuffer_width=$fb_width
framebuffer_height=$fb_height

# Force composite (ignore HDMI)
hdmi_ignore_hotplug=1

# Better audio on analog output
audio_pwm_mode=2
EOF
            ;;
    esac
    
    # Close pi4 section if opened
    if [[ "$PI_MODEL" == "pi4" ]]; then
        cat << EOF

[all]
EOF
    fi
    
    cat << EOF
$CONFIG_END
EOF
}

#
# cmdline.txt manipulation for color mode (Trixie/Bookworm)
#

# Set vc4.tv_norm in cmdline.txt
# Values: NTSC, NTSC-J, NTSC-443, PAL, PAL-M, PAL-N, PAL60, SECAM
set_cmdline_tv_norm() {
    local mode="$1"
    local cmdline_file=$(get_cmdline_file)
    
    # Remove existing vc4.tv_norm
    sed -i 's/ vc4.tv_norm=[^ ]*//' "$cmdline_file"
    
    # Append new value
    sed -i "s/$/ vc4.tv_norm=$mode/" "$cmdline_file"
    
    echo "Set vc4.tv_norm=$mode in $cmdline_file"
}

# Get current vc4.tv_norm from cmdline.txt
get_cmdline_tv_norm() {
    local cmdline_file=$(get_cmdline_file)
    grep -oE 'vc4.tv_norm=[^ ]+' "$cmdline_file" 2>/dev/null | cut -d= -f2 || echo "not set"
}

# Remove vc4.tv_norm from cmdline.txt
remove_cmdline_tv_norm() {
    local cmdline_file=$(get_cmdline_file)
    sed -i 's/ vc4.tv_norm=[^ ]*//' "$cmdline_file"
    echo "Removed vc4.tv_norm from $cmdline_file"
}

#
# High-level configuration functions
#

# Apply config to boot file
apply_boot_config() {
    local boot_mode="${1:-ntsc480i}"
    local color_mode="${2:-}"  # Optional: PAL60, NTSC, etc.
    
    init_platform
    
    local config_file=$(get_config_file)
    
    # Backup first
    backup_config
    
    # Disable conflicting overlays based on OS
    case "$OS_GENERATION" in
        trixie|bookworm)
            # Comment out any plain vc4-kms-v3d (we'll add ,composite version)
            disable_conflicting_overlays "kms"
            ;;
        bullseye)
            disable_conflicting_overlays "fkms"
            ;;
    esac
    
    # Remove existing toolkit config
    remove_our_config
    
    # Append new config
    generate_config "$boot_mode" >> "$config_file"
    
    # Set color mode in cmdline.txt if specified (for Trixie/Bookworm)
    if [[ -n "$color_mode" ]] && supports_feature cmdline_tv_norm; then
        set_cmdline_tv_norm "$color_mode"
    fi
    
    echo ""
    echo "Boot configuration updated for mode: $boot_mode"
    [[ -n "$color_mode" ]] && echo "Color mode set to: $color_mode"
    echo "Please reboot to apply changes."
}

# Read current boot config
get_boot_config() {
    local config_file=$(get_config_file)
    
    # Extract our section if it exists
    if grep -q "$CONFIG_START" "$config_file"; then
        sed -n "/$CONFIG_START/,/$CONFIG_END/p" "$config_file"
    else
        echo "No CRT Toolkit configuration found in $config_file"
    fi
}

# Validate config file
validate_config() {
    local config_file=$(get_config_file)
    local issues=()
    
    init_platform
    
    # Check for conflicting overlays
    local fkms_count=$(grep -cE "^dtoverlay=vc4-fkms-v3d" "$config_file" || echo 0)
    local kms_count=$(grep -cE "^dtoverlay=vc4-kms-v3d" "$config_file" || echo 0)
    
    if [[ "$fkms_count" -gt 1 ]]; then
        issues+=("Multiple vc4-fkms-v3d overlays found")
    fi
    
    if [[ "$kms_count" -gt 0 ]] && [[ "$fkms_count" -gt 0 ]]; then
        issues+=("Both fkms and kms overlays found - may conflict")
    fi
    
    # OS-specific checks
    case "$OS_GENERATION" in
        trixie|bookworm)
            # Should have ,composite
            if ! grep -qE "dtoverlay=vc4-kms-v3d,.*composite" "$config_file"; then
                issues+=("Missing dtoverlay=vc4-kms-v3d,composite for Trixie/Bookworm")
            fi
            ;;
        *)
            # Should have enable_tvout
            if ! grep -q "enable_tvout=1" "$config_file"; then
                issues+=("enable_tvout=1 not found - composite may not work")
            fi
            ;;
    esac
    
    if [[ ${#issues[@]} -eq 0 ]]; then
        echo "Configuration looks OK for $OS_GENERATION"
        return 0
    else
        echo "Configuration issues found:"
        for issue in "${issues[@]}"; do
            echo "  - $issue"
        done
        return 1
    fi
}

# CLI interface
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    case "${1:-}" in
        apply)
            apply_boot_config "${2:-ntsc480i}" "${3:-}"
            ;;
        show)
            get_boot_config
            ;;
        generate)
            init_platform
            generate_config "${2:-ntsc480i}"
            ;;
        validate)
            init_platform
            validate_config
            ;;
        backup)
            backup_config
            ;;
        tv-norm)
            if [[ -n "$2" ]]; then
                set_cmdline_tv_norm "$2"
            else
                echo "Current: $(get_cmdline_tv_norm)"
            fi
            ;;
        *)
            echo "Usage: $0 <command> [args]"
            echo ""
            echo "Commands:"
            echo "  apply <mode> [color]  - Apply boot config"
            echo "  show                  - Show current config"
            echo "  generate <mode>       - Generate config (dry run)"
            echo "  validate              - Check for issues"
            echo "  backup                - Backup config file"
            echo "  tv-norm [mode]        - Get/set vc4.tv_norm"
            echo ""
            echo "Modes: ntsc480i, ntsc240p, pal576i, pal288p"
            echo "Colors: NTSC, PAL, PAL60, NTSC-J, NTSC-443, PAL-M, PAL-N, SECAM"
            exit 1
            ;;
    esac
fi
