#!/bin/bash
#
# Pi CRT Toolkit - Boot Configuration
# Manages /boot/config.txt and cmdline.txt settings for CRT output
#
# Supports:
# - Buster (Debian 10): Legacy driver, /boot/config.txt
# - Bullseye (Debian 11): FKMS default, /boot/config.txt
# - Bookworm (Debian 12): Full KMS, /boot/firmware/config.txt
# - Trixie (Debian 13): Full KMS only, /boot/firmware/config.txt
#

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/platform.sh"

# Marker comments for our config section
CONFIG_START="# === Pi CRT Toolkit Start ==="
CONFIG_END="# === Pi CRT Toolkit End ==="

#
# Mode definitions
#

# sdtv_mode values (for FKMS/Legacy boot config)
declare -A SDTV_MODES=(
    ["ntsc480i"]=0     # NTSC 480i (default)
    ["ntsc240p"]=16    # NTSC 240p
    ["pal576i"]=2      # PAL 576i
    ["pal288p"]=18     # PAL 288p
)

# KMS video= cmdline parameters (for Bookworm/Trixie)
# Format: <width>x<height>@<refresh><flags>
# Flags: i=interlaced, e=enable (force on)
declare -A KMS_VIDEO_MODES=(
    ["ntsc480i"]="720x480@60ie"
    ["ntsc240p"]="720x240@60e"
    ["pal576i"]="720x576@50ie"
    ["pal288p"]="720x288@50e"
)

# tv_mode values for cmdline (KMS color encoding)
declare -A TV_MODE_VALUES=(
    ["ntsc"]="NTSC"
    ["ntsc-j"]="NTSC-J"
    ["ntsc-443"]="NTSC-443"
    ["pal"]="PAL"
    ["pal60"]="PAL"  # PAL color on 480i = PAL60-like
    ["pal-m"]="PAL-M"
    ["pal-n"]="PAL-N"
    ["secam"]="SECAM"
)

#
# File paths
#

get_config_file() {
    get_config_path
}

get_cmdline_file() {
    get_cmdline_path
}

#
# Backup
#

backup_config() {
    local config_file=$(get_config_file)
    local backup="${config_file}.bak.$(date +%Y%m%d-%H%M%S)"
    cp "$config_file" "$backup"
    echo "Backed up config to: $backup"
}

backup_cmdline() {
    local cmdline_file=$(get_cmdline_file)
    local backup="${cmdline_file}.bak.$(date +%Y%m%d-%H%M%S)"
    cp "$cmdline_file" "$backup"
    echo "Backed up cmdline to: $backup"
}

#
# config.txt manipulation
#

# Remove our config section
remove_our_config() {
    local config_file=$(get_config_file)
    sed -i "/$CONFIG_START/,/$CONFIG_END/d" "$config_file"
}

# Comment out conflicting dtoverlays
disable_conflicting_overlays() {
    local config_file=$(get_config_file)
    
    # Comment out any vc4 overlays we'll replace
    sed -i 's/^dtoverlay=vc4-fkms-v3d$/#&  # disabled by crt-toolkit/' "$config_file"
    sed -i 's/^dtoverlay=vc4-kms-v3d$/#&  # disabled by crt-toolkit/' "$config_file"
    sed -i 's/^dtoverlay=vc4-kms-v3d,/#&  # disabled by crt-toolkit was: /' "$config_file"
}

# Generate config.txt section
generate_config() {
    local boot_mode="${1:-ntsc480i}"
    local os_gen="${2:-$OS_GENERATION}"
    
    local sdtv_mode="${SDTV_MODES[$boot_mode]:-0}"
    
    cat << EOF
$CONFIG_START
# Generated by Pi CRT Toolkit
# OS: $os_gen, Mode: $boot_mode

EOF

    case "$os_gen" in
        trixie|bookworm)
            # KMS driver with composite option
            cat << EOF
# KMS driver with composite output
# IMPORTANT: Also requires video=Composite-1:... in cmdline.txt
dtoverlay=vc4-kms-v3d,composite=1
max_framebuffers=2

# Disable HDMI to ensure composite is primary
hdmi_ignore_hotplug=1

# Overscan off (handle per-game in RetroArch)
disable_overscan=1

# Better analog audio
audio_pwm_mode=2
EOF
            ;;
        bullseye)
            # FKMS - best for CRT, has tvservice
            cat << EOF
# FKMS driver (recommended for CRT - has tvservice)
dtoverlay=vc4-fkms-v3d
max_framebuffers=2

# Enable composite output
enable_tvout=1
sdtv_mode=$sdtv_mode
sdtv_aspect=1

# Disable HDMI to ensure composite is primary
hdmi_ignore_hotplug=1

# Overscan off (handle per-game in RetroArch)
disable_overscan=1

# Better analog audio
audio_pwm_mode=2
EOF
            ;;
        buster|*)
            # Legacy/FKMS
            cat << EOF
# Enable composite TV output
enable_tvout=1
sdtv_mode=$sdtv_mode
sdtv_aspect=1

# Disable HDMI to ensure composite is primary
hdmi_ignore_hotplug=1

# Overscan off
disable_overscan=1

# Better analog audio
audio_pwm_mode=2
EOF
            ;;
    esac
    
    cat << EOF
$CONFIG_END
EOF
}

#
# cmdline.txt manipulation (KMS - Bookworm/Trixie)
#

# Get current video= parameter value
get_cmdline_video() {
    local cmdline_file=$(get_cmdline_file)
    grep -oE 'video=Composite-1:[^ ]+' "$cmdline_file" 2>/dev/null | cut -d: -f2 || echo ""
}

# Set video= parameter for composite mode
# This is REQUIRED for KMS graphical apps to work!
set_cmdline_video() {
    local mode="${1:-ntsc480i}"
    local color="${2:-}"
    local cmdline_file=$(get_cmdline_file)
    
    local video_mode="${KMS_VIDEO_MODES[$mode]:-720x480@60ie}"
    
    # Build the video= parameter
    local video_param="video=Composite-1:$video_mode"
    
    # Add tv_mode if color specified
    if [[ -n "$color" ]]; then
        local tv_mode="${TV_MODE_VALUES[${color,,}]:-}"
        if [[ -n "$tv_mode" ]]; then
            video_param="${video_param},tv_mode=$tv_mode"
        fi
    fi
    
    # Read current cmdline
    local cmdline=$(cat "$cmdline_file")
    
    # Remove any existing video=Composite-1: parameter
    cmdline=$(echo "$cmdline" | sed 's/ video=Composite-1:[^ ]*//g')
    
    # Append new parameter
    cmdline="$cmdline $video_param"
    
    # Clean up extra spaces
    cmdline=$(echo "$cmdline" | tr -s ' ')
    
    # Write back (must be single line!)
    echo "$cmdline" > "$cmdline_file"
    
    echo "Set cmdline video=$video_mode"
    [[ -n "$color" ]] && echo "Set cmdline tv_mode=${TV_MODE_VALUES[${color,,}]:-$color}"
}

# Remove video= parameter
remove_cmdline_video() {
    local cmdline_file=$(get_cmdline_file)
    sed -i 's/ video=Composite-1:[^ ]*//g' "$cmdline_file"
    echo "Removed video=Composite-1 from cmdline"
}

# Legacy vc4.tv_norm handling (deprecated, use video= tv_mode instead)
get_cmdline_tv_norm() {
    local cmdline_file=$(get_cmdline_file)
    grep -oE 'vc4.tv_norm=[^ ]+' "$cmdline_file" 2>/dev/null | cut -d= -f2 || echo ""
}

set_cmdline_tv_norm() {
    local mode="$1"
    local cmdline_file=$(get_cmdline_file)
    
    # Remove existing
    sed -i 's/ vc4.tv_norm=[^ ]*//g' "$cmdline_file"
    
    # Append new
    sed -i "s/$/ vc4.tv_norm=$mode/" "$cmdline_file"
    echo "Set vc4.tv_norm=$mode"
}

#
# High-level functions
#

# Apply full boot configuration
apply_boot_config() {
    local boot_mode="${1:-ntsc480i}"
    local color_mode="${2:-}"
    
    init_platform
    
    local config_file=$(get_config_file)
    local cmdline_file=$(get_cmdline_file)
    
    echo "Applying boot configuration..."
    echo "  OS: $OS_GENERATION"
    echo "  Mode: $boot_mode"
    [[ -n "$color_mode" ]] && echo "  Color: $color_mode"
    echo ""
    
    # Backup files
    backup_config
    
    # Disable conflicting overlays
    disable_conflicting_overlays
    
    # Remove existing toolkit config
    remove_our_config
    
    # Append new config
    generate_config "$boot_mode" >> "$config_file"
    echo "Updated $config_file"
    
    # KMS requires cmdline.txt video= parameter
    if [[ "$OS_GENERATION" == "trixie" ]] || [[ "$OS_GENERATION" == "bookworm" ]]; then
        backup_cmdline
        set_cmdline_video "$boot_mode" "$color_mode"
        echo ""
        echo "IMPORTANT: KMS requires the video= parameter in cmdline.txt"
        echo "Without it, graphical applications cannot find the display!"
    fi
    
    echo ""
    echo "Configuration complete. Reboot to apply changes."
}

# Show current boot config
show_boot_config() {
    init_platform
    
    local config_file=$(get_config_file)
    local cmdline_file=$(get_cmdline_file)
    
    echo "=== Platform ==="
    echo "OS: $OS_CODENAME ($OS_GENERATION)"
    echo "Pi Model: $PI_MODEL"
    echo "Driver: $DRIVER"
    echo ""
    
    echo "=== config.txt ($config_file) ==="
    if grep -q "$CONFIG_START" "$config_file"; then
        sed -n "/$CONFIG_START/,/$CONFIG_END/p" "$config_file"
    else
        echo "(No CRT Toolkit section found)"
        echo ""
        echo "Relevant settings:"
        grep -E "dtoverlay=vc4|enable_tvout|sdtv_mode|hdmi_ignore" "$config_file" 2>/dev/null | head -10
    fi
    echo ""
    
    echo "=== cmdline.txt ($cmdline_file) ==="
    local video=$(get_cmdline_video)
    local tv_norm=$(get_cmdline_tv_norm)
    
    if [[ -n "$video" ]]; then
        echo "video=Composite-1:$video"
    else
        echo "video=Composite-1: (not set)"
        if [[ "$OS_GENERATION" == "trixie" ]] || [[ "$OS_GENERATION" == "bookworm" ]]; then
            echo "  WARNING: This is required for KMS graphical apps!"
        fi
    fi
    
    [[ -n "$tv_norm" ]] && echo "vc4.tv_norm=$tv_norm"
}

# Validate configuration
validate_config() {
    init_platform
    
    local config_file=$(get_config_file)
    local cmdline_file=$(get_cmdline_file)
    local issues=()
    local warnings=()
    
    echo "Validating configuration..."
    echo ""
    
    case "$OS_GENERATION" in
        trixie|bookworm)
            # Check for KMS with composite
            if ! grep -qE "dtoverlay=vc4-kms-v3d.*composite" "$config_file"; then
                issues+=("Missing dtoverlay=vc4-kms-v3d,composite=1 in config.txt")
            fi
            
            # Check cmdline.txt video=
            if [[ -z "$(get_cmdline_video)" ]]; then
                issues+=("Missing video=Composite-1:... in cmdline.txt (required for graphical apps!)")
            fi
            ;;
        bullseye)
            # Check for FKMS
            if ! grep -qE "^dtoverlay=vc4-fkms-v3d" "$config_file"; then
                warnings+=("FKMS overlay not found - tvservice may not work")
            fi
            
            # Check enable_tvout
            if ! grep -q "^enable_tvout=1" "$config_file"; then
                issues+=("enable_tvout=1 not found - composite output disabled")
            fi
            ;;
        buster|*)
            if ! grep -q "^enable_tvout=1" "$config_file"; then
                issues+=("enable_tvout=1 not found - composite output disabled")
            fi
            ;;
    esac
    
    # Check for conflicts
    local fkms=$(grep -c "^dtoverlay=vc4-fkms-v3d" "$config_file" 2>/dev/null || echo 0)
    local kms=$(grep -c "^dtoverlay=vc4-kms-v3d" "$config_file" 2>/dev/null || echo 0)
    
    if [[ "$fkms" -gt 0 ]] && [[ "$kms" -gt 0 ]]; then
        warnings+=("Both FKMS and KMS overlays found - may conflict")
    fi
    
    # Report
    if [[ ${#issues[@]} -eq 0 ]] && [[ ${#warnings[@]} -eq 0 ]]; then
        echo "✓ Configuration looks good for $OS_GENERATION"
        return 0
    fi
    
    if [[ ${#issues[@]} -gt 0 ]]; then
        echo "ISSUES (must fix):"
        for issue in "${issues[@]}"; do
            echo "  ✗ $issue"
        done
    fi
    
    if [[ ${#warnings[@]} -gt 0 ]]; then
        echo "WARNINGS:"
        for warn in "${warnings[@]}"; do
            echo "  ! $warn"
        done
    fi
    
    return 1
}

#
# CLI
#

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    case "${1:-}" in
        apply)
            apply_boot_config "${2:-ntsc480i}" "${3:-}"
            ;;
        show|status)
            show_boot_config
            ;;
        validate|check)
            validate_config
            ;;
        generate)
            init_platform
            generate_config "${2:-ntsc480i}"
            ;;
        cmdline-video)
            init_platform
            if [[ -n "$2" ]]; then
                set_cmdline_video "$2" "${3:-}"
            else
                echo "Current: $(get_cmdline_video)"
            fi
            ;;
        backup)
            backup_config
            backup_cmdline
            ;;
        --help|-h|help)
            cat << EOF
Pi CRT Toolkit - Boot Configuration

Usage: $0 <command> [args]

Commands:
  apply <mode> [color]   Apply boot config (config.txt + cmdline.txt)
  show                   Show current configuration
  validate               Check for issues
  generate <mode>        Generate config.txt section (dry run)
  cmdline-video [mode]   Get/set cmdline video= parameter
  backup                 Backup config files

Boot modes:
  ntsc480i   480i at 60Hz (default, recommended for menus)
  ntsc240p   240p at 60Hz (progressive, for games)
  pal576i    576i at 50Hz
  pal288p    288p at 50Hz

Color modes (optional):
  pal60      PAL color on 60Hz (recommended for retro gaming)
  ntsc       Standard NTSC
  pal        Standard PAL
  ntsc-j     Japanese NTSC
  ntsc-443   NTSC with PAL subcarrier

Examples:
  $0 apply ntsc480i pal60    # 480i with PAL60 color
  $0 show                     # Show current config
  $0 validate                 # Check for issues

Notes:
  - FKMS (Bullseye): Uses tvservice, best for CRT
  - KMS (Bookworm/Trixie): Requires cmdline.txt video= parameter
EOF
            ;;
        *)
            echo "Usage: $0 <apply|show|validate|generate|cmdline-video|backup|help>"
            exit 1
            ;;
    esac
fi
